<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Size
    |--------------------------------------------------------------------------
    |
    | This value sets the default size in pixels for all QR codes generated by
    | the application.
    |
    */

    'size' => 100,

    /*
    |--------------------------------------------------------------------------
    | Default Format
    |--------------------------------------------------------------------------
    |
    | This value sets the default format for all QR codes generated by the
    | application. Supported formats include 'png', 'eps', and 'svg'.
    |
    */

    'format' => 'png',

    /*
    |--------------------------------------------------------------------------
    | Default Error Correction Level
    |--------------------------------------------------------------------------
    |
    | This value sets the default error correction level for all QR codes
    | generated by the application. Supported levels include 'L', 'M', 'Q',
    | and 'H'.
    |
    */

    'error_correction' => 'L',

    /*
    |--------------------------------------------------------------------------
    | Default Margin
    |--------------------------------------------------------------------------
    |
    | This value sets the default margin for all QR codes generated by the
    | application.
    |
    */

    'margin' => 1,

    /*
    |--------------------------------------------------------------------------
    | Default Encoding
    |--------------------------------------------------------------------------
    |
    | This value sets the default encoding for all QR codes generated by the
    | application.
    |
    */

    'encoding' => 'UTF-8',

    /*
    |--------------------------------------------------------------------------
    | Default Background Color
    |--------------------------------------------------------------------------
    |
    | This value sets the default background color for all QR codes generated
    | by the application. The format is an array of RGB values.
    |
    */

    'background_color' => [255, 255, 255],

    /*
    |--------------------------------------------------------------------------
    | Default Foreground Color
    |--------------------------------------------------------------------------
    |
    | This value sets the default foreground color for all QR codes generated
    | by the application. The format is an array of RGB values.
    |
    */

    'foreground_color' => [0, 0, 0],
];
